export const toolsData = [
  {
    name: 'Công cụ tính tải lạnh cơ bản',
    slug: 'cong-cu-tinh-tai-lanh-co-ban',
    category: 'cooling-load',
    excerpt: 'Tính toán tải lạnh cho không gian nhỏ và vừa một cách nhanh chóng và chính xác.',
    description: {
      root: {
        children: [
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Công cụ tính tải lạnh cơ bản giúp bạn xác định công suất điều hòa cần thiết cho không gian của mình. Công cụ này phù hợp cho các phòng nhỏ đến vừa với diện tích từ 10-100m². Sử dụng các phương pháp tính toán tiêu chuẩn ASHRAE để đảm bảo độ chính xác cao.',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'root',
        version: 1,
      },
    },
    icon: 'calculator',
    toolType: 'calculator',
    url: '/data/tools/cong-cu-tinh-tai-lanh-co-ban',
    features: [
      { feature: 'Tính toán nhanh dựa trên diện tích và loại phòng' },
      { feature: 'Tự động điều chỉnh theo điều kiện khí hậu Việt Nam' },
      { feature: 'Hiển thị kết quả chi tiết với khuyến nghị' },
      { feature: 'Xuất báo cáo PDF' },
    ],
    inputs: [
      {
        parameter: 'Diện tích phòng',
        unit: 'm²',
        description: 'Diện tích sàn của phòng cần tính toán',
        required: true,
      },
      {
        parameter: 'Chiều cao trần',
        unit: 'm',
        description: 'Chiều cao từ sàn đến trần',
        required: true,
      },
      {
        parameter: 'Số người thường xuyên',
        unit: 'người',
        description: 'Số lượng người thường xuyên có mặt trong phòng',
        required: true,
      },
      {
        parameter: 'Loại phòng',
        unit: '',
        description: 'Văn phòng, phòng ngủ, phòng khách, v.v.',
        required: true,
      },
    ],
    outputs: [
      {
        result: 'Công suất làm lạnh cần thiết',
        unit: 'BTU/h',
        description: 'Công suất điều hòa khuyến nghị',
      },
      {
        result: 'Công suất dự phòng',
        unit: 'BTU/h',
        description: 'Công suất bổ sung cho điều kiện khắc nghiệt',
      },
    ],
    difficulty: 'easy',
    estimatedTime: '3-5 phút',
    tutorial: {
      root: {
        children: [
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Bước 1: Nhập diện tích và chiều cao phòng\nBước 2: Chọn loại phòng từ danh sách\nBước 3: Nhập số người thường xuyên\nBước 4: Nhấn tính toán để xem kết quả',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'root',
        version: 1,
      },
    },
    examples: [
      {
        title: 'Phòng ngủ 20m²',
        description: 'Tính toán cho phòng ngủ diện tích 20m², 2 người sử dụng',
        inputData: {
          area: 20,
          height: 2.7,
          people: 2,
          roomType: 'bedroom'
        },
        expectedOutput: {
          coolingLoad: '7200 BTU/h',
          recommendation: 'Máy lạnh 9000 BTU/h'
        },
      },
    ],
    tags: [
      { tag: 'HVAC' },
      { tag: 'điều hòa' },
      { tag: 'tính toán' },
      { tag: 'BTU' },
    ],
    featured: true,
    status: 'published',
  },
  {
    name: 'Công cụ so sánh hiệu suất máy lạnh',
    slug: 'cong-cu-so-sanh-hieu-suat-may-lanh',
    category: 'efficiency-comparison',
    excerpt: 'So sánh hiệu suất và chi phí vận hành của các loại máy lạnh khác nhau.',
    description: {
      root: {
        children: [
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Công cụ so sánh hiệu suất giúp bạn lựa chọn máy lạnh phù hợp bằng cách so sánh EER, SEER và chi phí vận hành của các mẫu máy khác nhau. Tính toán chi phí điện năng trong suốt vòng đời sử dụng để đưa ra quyết định đầu tư thông minh.',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'root',
        version: 1,
      },
    },
    icon: 'bar-chart-3',
    toolType: 'comparison',
    url: '/data/tools/cong-cu-so-sanh-hieu-suat-may-lanh',
    features: [
      { feature: 'So sánh EER và SEER của nhiều máy lạnh' },
      { feature: 'Tính toán chi phí điện năng hàng tháng và hàng năm' },
      { feature: 'Hiển thị biểu đồ so sánh trực quan' },
      { feature: 'Phân tích thời gian hoàn vốn' },
    ],
    inputs: [
      {
        parameter: 'Công suất máy lạnh 1',
        unit: 'BTU/h',
        description: 'Công suất của máy lạnh thứ nhất',
        required: true,
      },
      {
        parameter: 'EER máy lạnh 1',
        unit: '',
        description: 'Chỉ số hiệu suất năng lượng của máy 1',
        required: true,
      },
      {
        parameter: 'Công suất máy lạnh 2',
        unit: 'BTU/h',
        description: 'Công suất của máy lạnh thứ hai',
        required: true,
      },
      {
        parameter: 'EER máy lạnh 2',
        unit: '',
        description: 'Chỉ số hiệu suất năng lượng của máy 2',
        required: true,
      },
      {
        parameter: 'Giá điện',
        unit: 'VNĐ/kWh',
        description: 'Giá điện hiện tại',
        required: false,
      },
    ],
    outputs: [
      {
        result: 'Chi phí vận hành so sánh',
        unit: 'VNĐ/tháng',
        description: 'Chi phí điện ước tính hàng tháng cho từng máy',
      },
      {
        result: 'Tiết kiệm hàng năm',
        unit: 'VNĐ',
        description: 'Số tiền tiết kiệm được khi chọn máy hiệu suất cao',
      },
    ],
    difficulty: 'medium',
    estimatedTime: '5-7 phút',
    tags: [
      { tag: 'hiệu suất' },
      { tag: 'so sánh' },
      { tag: 'tiết kiệm điện' },
      { tag: 'EER' },
      { tag: 'SEER' },
    ],
    featured: true,
    status: 'published',
  },
  {
    name: 'Công cụ phân tích tiết kiệm năng lượng',
    slug: 'cong-cu-phan-tich-tiet-kiem-nang-luong',
    category: 'energy-savings',
    excerpt: 'Phân tích tiềm năng tiết kiệm năng lượng khi nâng cấp hệ thống HVAC.',
    description: {
      root: {
        children: [
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Công cụ phân tích giúp đánh giá tiềm năng tiết kiệm năng lượng khi thay thế hoặc nâng cấp hệ thống HVAC hiện tại. Tính toán ROI, thời gian hoàn vốn và lợi ích môi trường từ việc đầu tư vào công nghệ tiết kiệm năng lượng.',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'root',
        version: 1,
      },
    },
    icon: 'line-chart',
    toolType: 'analysis',
    url: '/data/tools/cong-cu-phan-tich-tiet-kiem-nang-luong',
    features: [
      { feature: 'Phân tích chi phí năng lượng hiện tại' },
      { feature: 'Ước tính tiết kiệm sau nâng cấp' },
      { feature: 'Tính toán thời gian hoàn vốn (ROI)' },
      { feature: 'Báo cáo tác động môi trường' },
    ],
    inputs: [
      {
        parameter: 'Công suất hệ thống hiện tại',
        unit: 'kW',
        description: 'Tổng công suất tiêu thụ của hệ thống HVAC hiện tại',
        required: true,
      },
      {
        parameter: 'Thời gian vận hành/ngày',
        unit: 'giờ',
        description: 'Số giờ vận hành trung bình mỗi ngày',
        required: true,
      },
      {
        parameter: 'Hiệu suất hệ thống mới',
        unit: '%',
        description: 'Mức cải thiện hiệu suất so với hệ thống cũ',
        required: true,
      },
      {
        parameter: 'Chi phí đầu tư',
        unit: 'VNĐ',
        description: 'Tổng chi phí nâng cấp hệ thống',
        required: true,
      },
    ],
    outputs: [
      {
        result: 'Tiết kiệm điện năng/tháng',
        unit: 'kWh',
        description: 'Lượng điện tiết kiệm được hàng tháng',
      },
      {
        result: 'Tiết kiệm chi phí/năm',
        unit: 'VNĐ',
        description: 'Số tiền tiết kiệm được hàng năm',
      },
      {
        result: 'Thời gian hoàn vốn',
        unit: 'năm',
        description: 'Thời gian để thu hồi chi phí đầu tư',
      },
    ],
    difficulty: 'medium',
    estimatedTime: '8-10 phút',
    tags: [
      { tag: 'tiết kiệm năng lượng' },
      { tag: 'phân tích' },
      { tag: 'ROI' },
      { tag: 'nâng cấp' },
    ],
    featured: false,
    status: 'published',
  },
  {
    name: 'Công cụ tư vấn giải pháp HVAC',
    slug: 'cong-cu-tu-van-giai-phap-hvac',
    category: 'solution-advisor',
    excerpt: 'Tư vấn giải pháp HVAC phù hợp dựa trên yêu cầu và điều kiện cụ thể.',
    description: {
      root: {
        children: [
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Công cụ tư vấn thông minh giúp lựa chọn giải pháp HVAC tối ưu dựa trên các yếu tố như loại tòa nhà, ngân sách, yêu cầu về hiệu suất và môi trường. Sử dụng thuật toán AI để đưa ra khuyến nghị chính xác.',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'root',
        version: 1,
      },
    },
    icon: 'settings',
    toolType: 'advisor',
    url: '/data/tools/cong-cu-tu-van-giai-phap-hvac',
    features: [
      { feature: 'Phân tích yêu cầu chi tiết' },
      { feature: 'Khuyến nghị giải pháp tối ưu' },
      { feature: 'So sánh các phương án khác nhau' },
      { feature: 'Tính toán chi phí đầu tư và vận hành' },
    ],
    inputs: [
      {
        parameter: 'Loại tòa nhà',
        unit: '',
        description: 'Văn phòng, nhà ở, công nghiệp, thương mại',
        required: true,
      },
      {
        parameter: 'Diện tích tổng',
        unit: 'm²',
        description: 'Tổng diện tích cần điều hòa',
        required: true,
      },
      {
        parameter: 'Ngân sách dự kiến',
        unit: 'VNĐ',
        description: 'Ngân sách đầu tư ban đầu',
        required: true,
      },
      {
        parameter: 'Mức độ ưu tiên tiết kiệm năng lượng',
        unit: '',
        description: 'Thấp, Trung bình, Cao',
        required: true,
      },
    ],
    outputs: [
      {
        result: 'Giải pháp khuyến nghị',
        unit: '',
        description: 'Loại hệ thống HVAC phù hợp nhất',
      },
      {
        result: 'Chi phí ước tính',
        unit: 'VNĐ',
        description: 'Tổng chi phí đầu tư dự kiến',
      },
      {
        result: 'Thời gian thi công',
        unit: 'tuần',
        description: 'Thời gian ước tính để hoàn thành dự án',
      },
    ],
    difficulty: 'hard',
    estimatedTime: '10-15 phút',
    tags: [
      { tag: 'tư vấn' },
      { tag: 'giải pháp' },
      { tag: 'HVAC' },
      { tag: 'AI' },
    ],
    featured: true,
    status: 'published',
  },
  {
    name: 'Công cụ kiểm tra tiêu chuẩn ASHRAE',
    slug: 'cong-cu-kiem-tra-tieu-chuan-ashrae',
    category: 'standards',
    excerpt: 'Kiểm tra hệ thống HVAC theo các tiêu chuẩn ASHRAE và quy chuẩn Việt Nam.',
    description: {
      root: {
        children: [
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Công cụ kiểm tra tuân thủ các tiêu chuẩn ASHRAE 90.1, 62.1 và các quy chuẩn kỹ thuật của Việt Nam. Đảm bảo hệ thống HVAC đáp ứng đầy đủ các yêu cầu về an toàn, hiệu suất và chất lượng không khí.',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'root',
        version: 1,
      },
    },
    icon: 'file-text',
    toolType: 'reference',
    url: '/data/tools/cong-cu-kiem-tra-tieu-chuan-ashrae',
    features: [
      { feature: 'Kiểm tra tuân thủ ASHRAE 90.1' },
      { feature: 'Đánh giá chất lượng không khí theo ASHRAE 62.1' },
      { feature: 'So sánh với quy chuẩn Việt Nam' },
      { feature: 'Tạo báo cáo tuân thủ' },
    ],
    inputs: [
      {
        parameter: 'Loại hệ thống',
        unit: '',
        description: 'VRV, Chiller, Split, Package',
        required: true,
      },
      {
        parameter: 'Công suất hệ thống',
        unit: 'RT',
        description: 'Tổng công suất làm lạnh',
        required: true,
      },
      {
        parameter: 'Lưu lượng gió tươi',
        unit: 'm³/h',
        description: 'Lưu lượng gió tươi cung cấp',
        required: true,
      },
    ],
    outputs: [
      {
        result: 'Mức độ tuân thủ',
        unit: '%',
        description: 'Tỷ lệ đáp ứng các tiêu chuẩn',
      },
      {
        result: 'Điểm cần cải thiện',
        unit: '',
        description: 'Danh sách các vấn đề cần khắc phục',
      },
    ],
    difficulty: 'hard',
    estimatedTime: '15-20 phút',
    tags: [
      { tag: 'ASHRAE' },
      { tag: 'tiêu chuẩn' },
      { tag: 'tuân thủ' },
      { tag: 'chất lượng không khí' },
    ],
    featured: false,
    status: 'published',
  },
  {
    name: 'Hướng dẫn thiết kế hệ thống ống gió',
    slug: 'huong-dan-thiet-ke-he-thong-ong-gio',
    category: 'guidelines',
    excerpt: 'Hướng dẫn tính toán và thiết kế hệ thống ống gió theo tiêu chuẩn.',
    description: {
      root: {
        children: [
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Công cụ hướng dẫn chi tiết cách thiết kế hệ thống ống gió hiệu quả, bao gồm tính toán kích thước ống, áp suất, vận tốc gió và lựa chọn phụ kiện phù hợp. Đảm bảo hiệu suất tối ưu và tiết kiệm năng lượng.',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'root',
        version: 1,
      },
    },
    icon: 'book-open',
    toolType: 'reference',
    url: '/data/tools/huong-dan-thiet-ke-he-thong-ong-gio',
    features: [
      { feature: 'Tính toán kích thước ống gió' },
      { feature: 'Phân tích tổn thất áp suất' },
      { feature: 'Lựa chọn vật liệu phù hợp' },
      { feature: 'Thiết kế layout tối ưu' },
    ],
    inputs: [
      {
        parameter: 'Lưu lượng gió',
        unit: 'm³/h',
        description: 'Tổng lưu lượng gió cần phân phối',
        required: true,
      },
      {
        parameter: 'Chiều dài ống chính',
        unit: 'm',
        description: 'Độ dài ống gió chính',
        required: true,
      },
      {
        parameter: 'Số lượng cửa gió',
        unit: '',
        description: 'Tổng số cửa gió cần lắp đặt',
        required: true,
      },
    ],
    outputs: [
      {
        result: 'Kích thước ống khuyến nghị',
        unit: 'mm',
        description: 'Đường kính hoặc kích thước ống phù hợp',
      },
      {
        result: 'Tổn thất áp suất',
        unit: 'Pa',
        description: 'Tổn thất áp suất của hệ thống',
      },
      {
        result: 'Công suất quạt cần thiết',
        unit: 'W',
        description: 'Công suất quạt để khắc phục tổn thất',
      },
    ],
    difficulty: 'hard',
    estimatedTime: '20-25 phút',
    tags: [
      { tag: 'thiết kế' },
      { tag: 'ống gió' },
      { tag: 'tính toán' },
      { tag: 'áp suất' },
    ],
    featured: false,
    status: 'published',
  },
];
